---
title: "Afleveringsopgave"
author: "Christian Præst Møller"
date: "2025-12-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(infer)
library(tidyverse)
library(ggplot2)

set.seed(1)
n <- 32
x <- runif(32, min = 0, max = 1)
y <- (1/5)*exp(x)
x
y

mean(y)
(1/n)*sum(y <= 0.25)
quantile(y, prob = 0.95)

v <- tibble(y)

test <- rep_sample_n(v,size = n,replace = TRUE, reps = 1000) |>
  summarize(gns = mean(y),e = (1/n)*sum(y <= 0.25),q = quantile(y,0.95))  


ggplot(data=test,  mapping = aes(x = gns)) +
geom_histogram(bins = 15)
ggplot(data=test,  mapping = aes(x = e)) +
geom_histogram(bins = 15)
ggplot(data=test,  mapping = aes(x = q)) +
geom_histogram(bins = 15)

test
 
abe <- v |>
  generate(reps = 1000, type = "bootstrap") |>
  calculate(y,stat = "mean")

test
abe 
 
abe |> 
  get_ci(gns, level = 0.95, type = NULL, point_estimate = NULL)




KI <- test |> 
  get_confidence_interval(level = 0.95, type = "percentile", point_estimate = m)

```
Instikt siger quantile giver noget forkert men skal lige kigge på definitionen


```{r}
library(infer)
library(tidyverse)
library(ggplot2)

set.seed(1)
n <- 32
x <- runif(32, min = 0, max = 1)
y <- (1/5)*exp(x)
x
y

e1 <- mean(y)
e2 <- (1/n)*sum(y <= 0.25)
e3 <-quantile(y, prob = 0.95)

v <- tibble(y)

test <- rep_sample_n(v,size = n,replace = TRUE, reps = 1000) 
test1 <-  test |>
  summarize(gns = mean(y))
test2 <- test |>
  summarize(e = (1/n)*sum(y <= 0.25))
test3 <- test |>
  summarize(q = quantile(y,0.95))
KI1 <- test1 |>
 get_confidence_interval(level = 0.95, type = "percentile", point_estimate = e1)   
KI2 <- test2 |>
 get_confidence_interval(level = 0.95, type = "percentile", point_estimate = e2)  
KI3 <- test3 |>
 get_confidence_interval(level = 0.95, type = "percentile", point_estimate = e3)  

ggplot(data=test1,  mapping = aes(x = gns)) +
geom_histogram(bins = 15) +
  labs(x = "Sample Mean") +
  labs(y = "Antal") +
  shade_confidence_interval(endpoints = KI1)

ggplot(data=test2,  mapping = aes(x = e)) +
geom_histogram(bins = 15) +
  labs(x = "Empirisk mål") +
  labs(y = "Antal") +
  shade_confidence_interval(endpoints = KI2)


ggplot(data=test3,  mapping = aes(x = q)) +
geom_histogram(bins = 15) +
  labs(x = "95% Fractil") +
  labs(y = "Antal") +
  shade_confidence_interval(endpoints = KI3)

```














'

del 2
```{r}
library(readr)
data1 <- read_csv("data/data/remote_sensing_sentinel2_2018.csv")
library(infer)
library(tidyverse)
library(ggplot2)

set.seed(1)


tabel <- data1 |>
  group_by(season) |>
  summarize(n(),mean(NDVI))

tabel



AAAH<- data1|>
  filter(season == "Summer")
AAAH

gnsFt <- AAAH |> 
  specify(NDVI ~ climate_zone) |>
  hypothesise(null = "independence") |>
  generate(reps = 10000, type = "permute") |>
  calculate(stat = "F") 

gnsFt|>
  visualize(bins = 10) +
  shade_p_value(obs_stat = F_test$stat, direction = "right") 
gnsFt|>
  get_p_value(obs_stat = F_test$stat, direction = "right")


gnstt <- data1 |>
  specify(NDVI ~ season) |>
  hypothesise(null = "independence") |>
  generate(reps = 10000, type = "permute") |>
  calculate(stat = "F") 

gnstt|>
  visualize(bins = 10) +
  shade_p_value(obs_stat = F_test$stat, direction = "right") 
gnstt|>
  get_p_value(obs_stat = F_test$stat, direction = "right")

gnsfe <- data1 |>
  filter(season == "Fall" | season == "Spring") |>
  specify(NDVI ~ season) |>
  hypothesise(null = "independence") |>
  generate(reps = 10000, type = "permute") |>
  calculate(stat = "diff in means", order = c("Fall", "Spring")) 

gnsfe|>
  visualize(bins = 10) +
  shade_p_value(obs_stat = Delta_mean$stat, direction = "both") 
gnsfe|>
  get_p_value(obs_stat = Delta_mean$stat, direction = "both")




gnses <- data1 |>
  filter(season == "Fall" | season == "Summer") |>
  specify(NDVI ~ season) |>
  hypothesise(null = "independence") |>
  generate(reps = 10000, type = "permute") |>
  calculate(stat = "diff in means", order = c("Fall", "Summer")) 

gnses|>
  visualize(bins = 10) +
  shade_p_value(obs_stat = Delta_mean$stat, direction = "both") 
gnses|>
  get_p_value(obs_stat = Delta_mean$stat, direction = "both")




gnssf <- data1 |>
  filter(season == "Summer" | season == "Spring") |>
  specify(NDVI ~ season) |>
  hypothesise(null = "independence") |>
  generate(reps = 10000, type = "permute") |>
  calculate(stat = "diff in means", order = c("Summer", "Spring")) 

gnssf|>
  visualize(bins = 10) +
  shade_p_value(obs_stat = Delta_mean$stat, direction = "both") 
gnssf|>
  get_p_value(obs_stat = Delta_mean$stat, direction = "both")



gnsGGG <- data1 |>
  filter(climate_zone == "cfa" | season == "bsk") |>
  specify(NDVI ~ climate_zone) |>
  hypothesise(null = "independence") |>
  generate(reps = 10000, type = "permute") |>
  calculate(stat = "diff in means", order = c("cfa", "bsk")) 

gnsGGG|>
  visualize(bins = 10) +
  shade_p_value(obs_stat = Delta_mean$stat, direction = "both") 
gnsGGG|>
  get_p_value(obs_stat = Delta_mean$stat, direction = "both")





ggplot(data=data1,  mapping = aes(x = factor(climate_zone), y = NDVI, fill= season)) +
  geom_boxplot()

ggplot(data=data1,  mapping = aes(x = factor(season), y = NDVI, fill= climate_zone)) +
  geom_boxplot(position = "dodge")
```
Spørgsmål 7:
```{r}
library(readr)
library(moderndive)
library(infer)
library(tidyverse)
library(ggplot2)

set.seed(38)
data1 <- read_csv("data/data/remote_sensing_sentinel2_2018.csv")


relevant <- data1 |>
  mutate(kryds = str_glue("{season}{climate_zone}"))|>
  select(kryds,NDVI)


relevant



lifeExp_model2 <- lm(NDVI ~ climate_zone+season
                    , data = data1)
get_regression_table(lifeExp_model2)




base <- lm(NDVI ~ climate_zone+season, data = data1)
get_regression_table(base)
gæt1 <- lm(NDVI ~ climate_zone+season+prev_month_air_temperature, data = data1)
get_regression_table(gæt1)
get_regression_summaries(gæt1)
gæt2 <- lm(NDVI ~ climate_zone+season+prev_month_soil_temperature, data = data1)
get_regression_table(gæt2)
get_regression_summaries(gæt2)
gæt3 <- lm(NDVI ~ climate_zone+season+prev_month_moisture, data = data1)
get_regression_table(gæt3)
get_regression_summaries(gæt3)
gæt4 <- lm(NDVI ~ climate_zone+season+soil_temperature_yearly, data = data1)
get_regression_table(gæt4)
get_regression_summaries(gæt4)
gæt5 <- lm(NDVI ~ climate_zone+season+moisture_yearly, data = data1)
get_regression_table(gæt5)
get_regression_summaries(gæt5)
gæt6 <- lm(NDVI ~ climate_zone+season+air_temperature_yearly, data = data1)
get_regression_table(gæt6)
get_regression_summaries(gæt6)




Gæt <-lm(NDVI~climate_zone+season+prev_month_air_temperature+prev_month_soil_temperature+prev_month_moisture,data = data1)
get_regression_summaries(Gæt)

F_test <- function(lm_null, lm_full) {
  p <- lm_full$rank
  q <- lm_null$rank
  
  numerator <- lm_full$df.residual * sum((lm_full$fitted.values -lm_null$fitted.values)^2)
  denominator <- sum(lm_full$residuals^2)*(p-q)
  
  return(numerator/denominator)
}


#1 prev month air temperaturev
statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_air_temperature, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")

#2 prev_month_soil_temperature
statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_soil_temperature, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")
#3 prev_month_moisture
statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_moisture, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")
#4 soil_temperature_yearly
statics_lm_stor <- lm(NDVI~ climate_zone+season+soil_temperature_yearly, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")
#5 moisture_yearly
statics_lm_stor <- lm(NDVI~ climate_zone+season+moisture_yearly, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")
#6 air_temperature_yearly
statics_lm_stor <- lm(NDVI~ climate_zone+season+air_temperature_yearly, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")




#7 Mit første og sidste bud på model
statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_air_temperature+prev_month_soil_temperature+prev_month_moisture, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")

#PERMUTATIONER FOR LOLS SKYlD
#8 -airtemp
statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_soil_temperature+prev_month_moisture, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")

#9 -soiltemp
statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_air_temperature+prev_month_moisture, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")

#10 -moist
statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_air_temperature+prev_month_soil_temperature, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")




```
Næste er udelukkende kontrol for at model #7 faktisk passer og alle tre variable er relevante samtidig.
```{r}
#De første tre er den store model minus en variabel.
statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_air_temperature+prev_month_soil_temperature+prev_month_moisture, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season+prev_month_air_temperature+prev_month_soil_temperature, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")
#------------------------------------------------------------------------------------------------------------------------------------
statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_air_temperature+prev_month_soil_temperature+prev_month_moisture, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season+prev_month_soil_temperature+prev_month_moisture, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")
#----------------------------------------------------------------------------------------------
statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_air_temperature+prev_month_soil_temperature+prev_month_moisture, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season+prev_month_air_temperature+prev_month_moisture, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")
#--------------------------------------------------------------------------------------------------------------------
# viderudvilklinger fra airtemp

statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_air_temperature+prev_month_soil_temperature, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season+prev_month_air_temperature, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")

statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_air_temperature+prev_month_moisture, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season+prev_month_air_temperature, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")

#------------------------------------------------------------------------------------------------------------------------
# viderudvilklinger fra soiltemp

statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_soil_temperature+prev_month_air_temperature, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season+prev_month_soil_temperature, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")

statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_soil_temperature+prev_month_moisture, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season+prev_month_soil_temperature, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")

#------------------------------------------------------------------------------------------------------------------------
# viderudvilklinger fra moist

statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_moisture+prev_month_air_temperature, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season+prev_month_moisture, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")

statics_lm_stor <- lm(NDVI~ climate_zone+season+prev_month_moisture+prev_month_soil_temperature, data = data1)
statics_lm <- lm(NDVI~ climate_zone + season+prev_month_moisture, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")

#------------------------------------------------------------------------------------------------------------------------
```
Kan den være mindre?
```{r}
statics_lm_stor <- lm(NDVI~ climate_zone+season, data = data1)
statics_lm <- lm(NDVI~ climate_zone, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")

statics_lm_stor <- lm(NDVI~ climate_zone+season, data = data1)
statics_lm <- lm(NDVI~ season, data = data1)
F_obs <- F_test(statics_lm, statics_lm_stor)
B <- 1000
X0 <- model.matrix(statics_lm)
X1 <- model.matrix(statics_lm_stor)
statics_boot <- tibble(residuals = residuals(statics_lm)) %>%
  rep_sample_n(size = nrow(data1), replace = TRUE, reps = B) %>%
  mutate(y = fitted(statics_lm) + residuals) %>%
  summarize(F = F_test(lm.fit(X0, y), lm.fit(X1, y)))


ggplot(data=statics_boot) +
  geom_histogram(mapping = aes(x=F))


statics_boot %>%
  get_p_value(obs_stat = F_obs, direction = "right")
```

